apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: ingress-nginx
  labels:
    app: ingress-nginx
spec:
  externalTrafficPolicy: Local
  selector:
    app: ingress-nginx
  ports:
  - name: http
    port: 80
    targetPort: http
  type: LoadBalancer
