apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  namespace: ingress-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
        track: stable
    spec:
      containers:
        - name: web
          image: gcr.io/assessing--kubernetes/kube:0.0.1
          args: ["bundle","exec","rails","server","--port","3100","--binding","0.0.0.0"]
          env:
            - name: RAILS_ENV
              value: production
            - name: ASSESSING-KUBERNETES_DATABASE_HOST
              value: 127.0.0.1 # Local, because using cloudproxy
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: assessing-kubernetes-secrets
                  key: rails_master_key
            - name: ASSESSING-KUBERNETES_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: assessing-kubernetes-secrets
                  key: db_pass
          ports:
            - name: http
              containerPort: 3100
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=assessing--kubernetes:us-central1:kube-mysql=tcp:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
